package(default_visibility = ["//visibility:public"])

cc_binary(
  name = "exam_scores",
  srcs = ["exam_scores.cc"],
)

cc_binary(
  name = "sum",
  srcs = ["sum.cc"],
)

cc_binary(
  name = "person_customer_data",
  srcs = ["person_customer_data.cc"],
)

cc_binary(
  name = "preferred_customer",
  srcs = ["preferred_customer.cc"],
)
