package(default_visibility = ["//visibility:public"])

cc_binary(
  name = "lottery",
  srcs = ["lottery.cc"],
)

cc_binary(
  name = "ackermann",
  srcs = ["ackermann.cc"],
)

cc_binary(
  name = "reverse",
  srcs = ["reverse.cc"],
)

cc_binary(
  name = "search_benchmark",
  srcs = ["search_benchmark.cc"],
)
