package(default_visibility = ["//visibility:public"])

cc_binary(
  name = "least_greatest",
  srcs = ["least_greatest.cc"],
)

cc_binary(
  name = "random_number_guessing",
  srcs = ["random_number_guessing.cc"],
)

cc_binary(
  name = "lowest_score",
  srcs = ["lowest_score.cc"],
)

cc_binary(
  name = "is_prime",
  srcs = ["is_prime.cc"],
)

cc_binary(
  name = "payroll",
  srcs = ["payroll.cc"],
)
