package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "stock_commission",
    srcs = ["stock_commission.cc"],
)

cc_binary(
    name = "angle_calculator",
    srcs = ["angle_calculator.cc"],
)

cc_binary(
    name = "monthly_payments",
    srcs = ["monthly_payments.cc"],
)

cc_binary(
    name = "freezing_boiling_points",
    srcs = ["freezing_boiling_points.cc"],
)

cc_binary(
    name = "mobile_service_provider",
    srcs = ["mobile_service_provider.cc"],
)
